---
exclude: ['Rakefile', 'README.markdown', '_design', 'Gemfile', 'Gemfile.lock']
markdown: redcarpet
redcarpet:
    extensions: ['smart', 'no_intraemphasis', 'tables']
permalink: pretty
pygments: true
safe: false
host: gamecook.com
navigation:
- text: Game Recipes
  url: /
- text: Games & Projects
  url: /games/
- text: HTML5 Game Dev Book
  url: /book/
- text: About GameCook
  url: /about/
  layout: post